### ISSUE TITLE
Why did you remove the git history?

### ISSUE THREAD

**Issue by oliverpool** [oliuz/teamwork#1]
Your repo: https://github.com/oliuz/teamwork/commits/master

Original repo: https://github.com/mpociot/teamwork/commits/master

**Comment by oliuz** [comment]
Hi @oliverpool ,

I did not remove the git history, since this repository is not a fork, I downloaded the package and uploaded it to my account to be able to use it with the changes. Therefore, when I upload it,   it does not have this history.

**Comment by oliverpool** [comment]
> this repository is not a fork

Well, you copied all the source code, so according to [wikipedia](https://en.wikipedia.org/wiki/Fork_(software_development)) this is a fork:

> In software engineering, a project fork happens when developers take a copy of source code from one software package and start independent development on it, creating a distinct and separate piece of software.

**Comment by oliverpool** [comment]
By doing the copy, you could have chosen to keep the git history, but you didn't. I would like to know why (maybe it's only because you didn't know how to keep it)

**Comment by oliuz** [comment]
I go back and repeat, just downloaded the ZIP, makes changes and upload to the repository. Nothing is deleted! Since this is not a fork.

**Comment by rehmatworks** [comment]
Whatever you call it, either a fork or a downloaded copy, initially the original developers should stay active to accept pull requests or to make it compatible to latest Laravel framework version. If they don't, we don't care about the git history. Keep up the good work @oliuz.
