### ISSUE TITLE
Make owner_id field optional when creating a team.

### ISSUE THREAD

**Issue by adistoica** [oliuz/teamwork#10]
In TeamworkTeam.php the boot() needs to have 

```
static::creating(function ($model) {
            $model->uuid = (string)Uuid::uuid1();
            $model->slug = Str::slug($model->name);
            $model->owner_id = auth()->user()->getKey(); // we don't have a auth() user yet.. here it breaks
        });
```

When I'm creating a team on Registration, obviously it is not possible anymore since the user is not yet authenticated.
On the previous version, I did manually assign the owner id when creating the team

```

 $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
)]

$team = $teamModel::create([
            'name' => $user->email,
            'owner_id' => $user->id // notice that we don't need an autheticated user here
        ]);
```

**Comment by oliuz** [comment]
A user is always required for team creation.

**Comment by jadamec** [comment]
What about creating teams during User Registration? In this case `auth()->user()->getKey()` is very bad option...
