### ISSUE TITLE
laravel 8 update

### ISSUE THREAD

**Issue by nsbucky** [oliuz/teamwork#11]
Do you think you will update this package to support laravel 8? Thanks

**Comment by oliuz** [comment]
Hi @nsbucky 

Yes, I am working on that update.

**Comment by siarheipashkevich** [comment]
@oliuz could you please make a patch for 7.1.* version for supporting laravel 8 ?

**Comment by nsbucky** [comment]
awesome thanks

**Comment by oliuz** [comment]
Was launched released the update for laravel 8 compatibility.
