### ISSUE TITLE
Breaking changes: renaming column current_team_id to current_team

### ISSUE THREAD

**Issue by siarheipashkevich** [oliuz/teamwork#12]
Why did you rename the column name from `current_team_id` to `current_team`? Please revert this changes because `_id` more preferred for foreign keys in the database.

https://github.com/oliuz/teamwork/commit/51f671e95fd3883f96757078abe6586a1b23f426
https://github.com/oliuz/teamwork/commit/ae58c8eaae1512c83e8d8828f576aea04f9237d9

**Comment by siarheipashkevich** [comment]
@oliuz could you please answer to this issue?

**Comment by oliuz** [comment]
Hi @siarheipashkevich 

This conversion was carried out, because if Jetstream is installed it does not bring an error when performing migrations, because it installs the same field by default.

**Comment by siarheipashkevich** [comment]
I'm not going to use jetstream package. BTW: in the jetstream package foreign key for team table is current_team_id and not current_team.
Can you make your package more better please?

**Comment by oliuz** [comment]
Hi @siarheipashkevich, update the package and export the config file with the following command: 
`php artisan vendor:publish --provider="Mpociot\Teamwork\TeamworkServiceProvider" --tag="teamwork-config"` 
and your problem will be solved.
