### ISSUE TITLE
How to avoid updating uuid?

### ISSUE THREAD

**Issue by siarheipashkevich** [oliuz/teamwork#14]
Hi @oliuz could you please assist me how I can avoid issue which I described above. In the latest version I can see that you moved this logic to `boot` method but it's not resolve my problem.

PS: I don't need `uuid` column in my `teams` table

I see 2 possible solutions:
1) don't extend `TeamworkTeam` model and just use `TeamworkTeamTrait` directly in my `Team` model. 
2) try to suppress your attached listeners in the `boot` method

**Comment by oliuz** [comment]
Hi @siarheipashkevich ,

What is the version of the package you use? Did you export the configuration file as I mentioned before?

**Comment by siarheipashkevich** [comment]
7.2+ version because from this version you added this logic.
Yes, I did. but the main issue is forced added `slug` and `uuid` columns to table and the logic for these fields in the `boot` method.

**Comment by oliuz** [comment]
Hi,

I understand that this is resolved with the PR you submitted.

**Comment by siarheipashkevich** [comment]
@oliuz it's not resolved in my previous PR.
