### ISSUE TITLE
Bug in namespacing ?

### ISSUE THREAD

**Issue by poppabear8883** [oliuz/teamwork#17]
```
Mpociot\Teamwork\Teamwork::acceptInvite(): Argument #1 ($invite) must be of type Mpociot\Teamwork\TeamInvite,
Mpociot\Teamwork\Models\TeamInvite given, called in 
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261
```

This comes straight from your published assets.
```php
public function __invoke($token)
    {
        $invite = Teamwork::getInviteFromAcceptToken($token);
        if (!$invite) {
            abort(404);
        }

        if (auth()->check()) {
            Teamwork::acceptInvite($invite);
            return redirect()->route('teams.index');
        } else {
            session(['invite_token' => $token]);
            return redirect()->to('login');
        }
    }
```

From your source, the type hint has no namespace or use statement so PHP assumes the same namespace as the file:
```php
/**
     * @param TeamInvite $invite
     */
    public function acceptInvite(TeamInvite $invite)
    {
        $this->user()->attachTeam($invite->team);
        $invite->delete();
    }
```

**Comment by smithdp1** [comment]
I have same problem. Did you find work around?

**Comment by smithdp1** [comment]
nevermind i used
`use Mpociot\Teamwork\Models\TeamInvite;`

**Comment by poppabear8883** [comment]
@smithdp1 This repository appears to just be a hacked up version of <https://github.com/mpociot/teamwork>.

I have switched over to use that repository.

**Comment by oliuz** [comment]
Hi @poppabear8883 

No, this repository is not a hacked version, at one point it was unattended and I took the course, and then they took it up again and I continued with my changes apart from the other. Thanks for reporting this bug!
