### ISSUE TITLE
Make uuid and slug column as optional

### ISSUE THREAD

**Issue by siarheipashkevich** [oliuz/teamwork#8]
Could you please make the uuid and slug columns as optional. Because your logic in the `boot` method from TemworkTeam model break my code. I don't need these fields `uuid` and `slug`

**Comment by oliuz** [comment]
Hi @siarheipashkevich 


Could you show the error it throws at you?

Thanks!

**Comment by siarheipashkevich** [comment]
Hi @oliuz 

My error is related to that you are setting the `uuid` and `slug` columns in the constructor but these fields doesn't exist in my `teams` table which was created 2 years ago.
I'm getting an sql error that the columns doesn't exists during creating or updating team record.

**Comment by oliuz** [comment]
The issue has solved in the last version for this package.

**Comment by siarheipashkevich** [comment]
Hi @oliuz could you please assist me how I can avoid issue which I described above. In the latest version I can see that you moved this logic to `boot` method but it's not resolve my problem.

PS: I don't need `uuid` column in my `teams` table

I see 2 possible solutions:
1) don't extend `TeamworkTeam` model and just use `TeamworkTeamTrait` directly in my `Team` model. 
2) try to suppress your attached listeners in the `boot` method
