### ISSUE TITLE
Don't update uuid column after each updating of the team

### ISSUE THREAD

**Issue by siarheipashkevich** [oliuz/teamwork#9]
Hi @oliuz 

I think that the logic of updating uuid column during updating team model incorrect. There is maybe case that we can lose relation to the team after updating team. 

Simple example: we create team record and user which will be related to this team

**creating process**:
`team table`:
uuid: 'uuid1'

`user table`:
id: 1
team_uuid: 'uuid1' - relation to team table

but after updating the team model the uuid column will be updated and the user will lose relation with the company by uuid

What do you think about this?

**Comment by oliuz** [comment]
no @siarheipashkevich , because the foreign key relationship is still by id not by another field!
